# Generated by Django 4.2.16 on 2024-11-24 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pereval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevalimage',
            name='pereval_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_pereval.pereval'),
        ),
    ]
