# Generated by Django 4.2.16 on 2024-12-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pereval', '0003_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('pnd', 'На модерации'), ('acp', 'Принято'), ('rej', 'Отклонено')], default='new', max_length=3),
        ),
    ]
